# Generated by Django 4.2.6 on 2023-10-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeds',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
